### ISSUE TITLE
Use OIDC for ArgoCD

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/devops-stack#251]

**Comment by mcanevet** [comment]
I couldn't make it work yet for k3s/k3os because keycloak, does not have a valid certificate and ArgoCD does not like it...

**Comment by modridi** [comment]
https://github.com/argoproj/argo-cd/issues/4344#issuecomment-693651844

**Comment by mcanevet** [comment]
https://github.com/argoproj/argo-cd/issues/4344#issuecomment-792677236

**Comment by mcanevet** [comment]
https://github.com/argoproj/argo-cd/issues/4344#issuecomment-792677236
