### ISSUE TITLE
Password retrivial

### ISSUE THREAD

**Issue by pburgisser** [camptocamp/devops-stack#582]
Docs in https://github.com/camptocamp/devops-stack/blob/master/docs/modules/ROOT/partials/inspect_apps.adoc mentiones we can access to ArgoCD with the password we have retrivied, but where is it documented?

**Comment by themreza** [comment]
The guide mentions to retrieve the admin_password terraform output, but the outputs.tf file in the guide doesn't contain it:
https://devops-stack.io/docs/devops-stack/0.33.2/howtos/quickstart_k3s_docker.html#_get_kubeconfig_and_admin_password

This, however, does:
https://github.com/camptocamp/devops-stack/blob/master/tests/k3s-docker/terraform/outputs.tf#L52
