### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by pburgisser** [camptocamp/devops-stack#587]
As doesn't mac doesn't support bridge0, we cannot access to container IP:port

**Comment by pburgisser** [comment]
We can make it work by playing with 127.0.0.1
@mcanevet Can we ensure that traefik is always running on the agent? so we can expose the port 80 and 443 on that pod and change the base domain to 127-0-0-1.nip.io (testing this solution right now)

**Comment by mcanevet** [comment]
@pburgisser I suppose you are talking about the k3s-libvirt variant.
How do you usually do to connect to a service running in a Virtual Machine? Does libvirt creates a NAT network that allows to access the VM from the Hypervisor?

**Comment by pburgisser** [comment]
No, I'm speaking about the k3s-docker variant.
If I publish the port 6443, 80 and 443 and change the base domain to 127-0-0-1.nip.io, terraform looks to be able to talk to argocd and start the applications

**Comment by mcanevet** [comment]
This is weird. I don't know how Docker is supposed to work on Mac OS, but I guess the default route of the containers points to an interface mounted on Mac OS so that the containers have a functional outgoing traffic, and hence you should be able to connect to the container from your hosting machine using this interface...
Unfortunately, I don't have any Mac OS to test this.

**Comment by pburgisser** [comment]
Actually, Docker doesn't run natively on Mac but through a VM, the whole thing is managed by docker (the vm etc...).
Official documentation says we have to expose ports [1] instead of connecting directly to container's IP.

My idea as mentioned earlier is to expose port 6443, 80 and 443 and use 127-0-0-1.nio.io as the base domain. I did some tests in the morning and it looks to work like this, I'm just stuck with memory consumption at the moment.

Don't worry about Mac, I'll do it with mine but we should invest a bit of time to make it run on Mac too as it's a quite used platform.

[1] https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

**Comment by mcanevet** [comment]
OK, that's clear now. I'd say we need 2 new variables to the k3s-docker variant:
- a `publish_ports` boolean to enable publishing ports `80` and `443`,
- a string that allows to set `domain_name` like on other variants (127-0-0-1.nip.io in your case).

I also wanted to add this 2 variables to allow access from the outside if you configure Port Address Translation on your router (no matter if you use Linux or Mac).

**Comment by pburgisser** [comment]
We'll have to add that to the k3s module too as the port is published when you startup the containers.

**Comment by pburgisser** [comment]
Hmmm, the fact we are using keycloak.apps.127-0-0-1.nip.io, oAuth proxy complains it can't contact 127.0.0.1:443

**Comment by mcanevet** [comment]
You should be able to use the IP address of your Mac, not 127-0-0-1.nip.io.
For example: 192-168-0-2.nip.io

**Comment by pburgisser** [comment]
Yes I can use this, but the api certificate has the SAN for container IP and 127.0.0.1.
If I use the laptop IP, kubectl complains about the certificate

**Comment by mcanevet** [comment]
It shouldn't have the SAN for 127.0.0.1 if you set `base_domain` to the IP of your workstation, not 127.0.0.1.

**Comment by mcanevet** [comment]
I'm wondering how to properly publish the ports in the docker-k3s module.
According to the documentation : https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#publish_all_ports, there is a `publish_all_ports` parameter, but I guess it would work only work if we expose the ports, which we do not do. We would have to explicitly expose the ports `80` and `443` on the server.
We could also allow to pass an arbitrary list of `ports` ; that would be more flexible for sure, but maybe difficult to use.

**Comment by mcanevet** [comment]
Something like that may work: https://github.com/camptocamp/terraform-docker-k3s/pull/11 (I didn't test though)

**Comment by pburgisser** [comment]
Have a look what I did to make it accessible from localhost
https://github.com/pburgisser/terraform-docker-k3s/blob/be3b14192727d5a40a89162b7020e160472871ed/main.tf#L79-L92
It's still WIP though

**Comment by mcanevet** [comment]
Yes, that's basically what my PR will allow to do. I prefer to not hard coding this in the module because it would block the capacity to spawn multiple stacks in parallel because the port would be taken.

**Comment by pburgisser** [comment]
As I said, it's a WIP and the time I took to push my code you did it :-)

**Comment by mcanevet** [comment]
@pburgisser I released a new version of the docker-k3s module that allows to publish ports on the K3s server.

**Comment by mcanevet** [comment]
@pburgisser let's wait for integration tests on #584

**Comment by mcanevet** [comment]
Once #584 is merged, I'll be able to rebase and merge #589.
Then, the only part missing will be to allow override of `base_domain`, and we should be able to address your issue (and more).

**Comment by mcanevet** [comment]
@pburgisser I think you can approve #584. The integration test failure on update is "normal" because the cluster will be recreated and hence the kubeconfig will change and Terraform can't know the new value before applying.

**Comment by mcanevet** [comment]
And here is the last need patch I think #590

**Comment by mcanevet** [comment]
Note that this series of patches will also optionally allow to access the cluster from the Internet if you configure your router to do Port Address Translation to the workstation and hence we should be able to honor Let's Encrypt HTTP01 challenge.

**Comment by mcanevet** [comment]
Last patch to merge: #589

**Comment by pburgisser** [comment]
@mcanevet I think there is a missing step: we need should be able to set the ports array when instanciating the devops stack modules/k3s/docker. No ?

**Comment by pburgisser** [comment]
So, it works better on mac now but I had to do some patch on the k3s module (see my PR [1])
Once my PR merged, I'll change the code here to allow to specify the publishing port.

I'm wondering still if there is an issue with the presented certificate as chrome refuse to let me in telling:
> argocd.apps.192-168-1-118.nip.io normally uses encryption to protect your information. When Google Chrome tried to connect to argocd.apps.192-168-1-118.nip.io this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be argocd.apps.192-168-1-118.nip.io, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
> 
> You cannot visit argocd.apps.192-168-1-118.nip.io at the moment because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

Good work!

[1] https://github.com/camptocamp/terraform-docker-k3s/pull/12

**Comment by pburgisser** [comment]
It works like a charm, thanks @mcanevet.
Closing the issue.
