### ISSUE TITLE
Ability to use podman instead of Docker

### ISSUE THREAD

**Issue by pburgisser** [camptocamp/devops-stack#59]
Some Linux distrubution such as RHEL 8 or some Fedora don't offer Docker anymore but podman instead. Having the possibility one of the them could be a cool feature.

**Comment by mcanevet** [comment]
I'm not sure this is possible using Terraform as podman does not have a daemon to talk to.

**Comment by mcanevet** [comment]
Actually this is maybe possible : https://podman.io/blogs/2020/07/01/rest-versioning.html

**Comment by mcanevet** [comment]
I have to test with that : http://crunchtools.com/a-first-look-at-the-podman-2-0-api/

**Comment by mcanevet** [comment]
It tried with podman 2.2 using the docker API and the terraform provider.
What works:
- pulling image
- creating network
- creating volumes
- creating container
But, connecting network to container is not possible in rootless mode.
