### ISSUE TITLE
Add optional deployment

### ISSUE THREAD

**Issue by deromemont** [camptocamp/devops-stack#645]
It's more a proposal than an issue

Try to add some option in code to add optional deployment

For example, option for loki, for cognito, ...

I know that argocd is interdependent with cognito for example
There a way to solve this ?

**Comment by raphink** [comment]
@deromemont the devops-stack now has `extra_apps`, `extra_application_sets` and `extra_app_projets` arguments for this.

With this, you can configure ArgoCD to deploy more applications.
