### ISSUE TITLE
Non descriptive names for apps of apps

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/devops-stack#660]
From what I understand, the apps structure is as follows:
```
app-of-apps:
- apps:
- - argocd
- - traefik
- - etc...
- extra_apps:
- - ...
```
The names are not descriptive enough. I suggest that "apps" be renamed to something like "devops-stack-apps" and maybe "app-of-apps" be renamed "root-apps" or something like that (because it's not the only app of apps).

**Comment by mcanevet** [comment]
Issue moved to Jira.
