### ISSUE TITLE
portainer add-on with default script

### ISSUE THREAD

**Issue by balasu** [camptocamp/devops-stack#796]
Hi

Portainer is a free, open source toolset for managing containerized applications. It works with Kubernetes, Docker, Docker Swarm, Azure ACI in both data centres and at the edge.

Portainer removes the complexity associated with orchestrators so developers can deploy apps quickly, easily and accurately. In addition to managing apps, it can be used to observe the behavior of containers, manage the underlying platform and provide the security and governance necessary for organization to deploy containers widely.
This add-on service will be enabled on nodeport 30777 and internally runs on 9000 port.
As part installation this add-on should be installed by default. document about portainer https://docs.portainer.io/v/ce-2.9/
pl guide me adding this add-on

**Comment by raphink** [comment]
Portainer is a very nice application, but we feel the DevOps Stack already provides the necessary features for this. In particular, the ArgoCD interface allows to view all the resources managed by the stack. You can also use non-invasive, client-side tools such as Lens or K9s for the same purpose.

If you really want to use Portainer with the DevOps Stack, you can pass it as an extra application to the stack for ArgoCD to manage it.
