### ISSUE TITLE
k3s/Docker Examples with unmatching docs

### ISSUE THREAD

**Issue by madduci** [camptocamp/devops-stack#801]
Hi

I'm trying to use the k3s/Docker example from the website, but I have the following problem:

In the `main.tf` file I have.

```terraform
module "cluster" {
  source = "git::https://github.com/camptocamp/devops-stack.git//modules/k3s/docker?ref=master"
  node_count   = 1
  cluster_name = "k3s-cluster"
  k3s_version = "v1.22.2+k3s2"
}
```
and it gives the following output on `terraform apply`:

```ssh
 ╷
│ Error: Unsupported argument
│ 
│   on main.tf line 11, in module "cluster":
│   11:   node_count   = 1
│ 
│ An argument named "node_count" is not expected here.
```

How can I declare to use only one node? My terraform version is the 1.0.9.

**Comment by raphink** [comment]
Hello,

The nodes are specified using the `worker_groups` parameter, as documented in https://devops-stack.io/docs/devops-stack/latest/references/terraform_modules/k3s/docker.html#input_worker_groups . E.g:

```
worker_groups = {
  "default": {
    "node_count": 1,
    "node_labels": [],
    "node_taints": []
  }
}
```
