### ISSUE TITLE
Add OVH Kubernetes Provider

### ISSUE THREAD

**Issue by armandleopold** [camptocamp/devops-stack#903]
Hello, nice work ! would it be difficult to add support for OVH cloud provider ? 

It seem's they have a terraform provider : [https://registry.terraform.io/providers/ovh/ovh/latest/docs](https://registry.terraform.io/providers/ovh/ovh/latest/docs)

**Comment by fsismondi** [comment]
Hello @armandleopold 
I guess it really depends on the status of the OVH provider. I wonder if you have any experiences using this OVH provider and/or using their k8s service?

**Comment by armandleopold** [comment]
Yes i do. A little. It provides a kubernetes cluster pretty easily.

**Comment by fsismondi** [comment]
@armandleopold thank you for your interest.

In camptocamp we don't currently manage ovh k8s clusters, so we are not planning on our side to work on it, yet, we would happily provide you support for doing so.

For the time being we are focusing in aks, eks, sks, scaleway and some other. As the amount of providers supported augments, we have chosen to re-designing the interfaces for easing this. This will be materialized into our soon-to-be-released DevOps Stack v1, [see more](https://dev.to/camptocamp-ops/towards-a-modular-devops-stack-257c)
