### ISSUE TITLE
Pass EKS module in v18

### ISSUE THREAD

**Issue by deromemont** [camptocamp/devops-stack#905]
EKS is now in v18
Try to pass the EKS module in this version

**Comment by modridi** [comment]
It's in progress.

**Comment by modridi** [comment]
Hi, thank you for showing interest in this project. The change you're suggesting will soon be available in the next major release that we're actively working on.

**Comment by lentidas** [comment]
This has been done after we separated the modules. The module on https://github.com/camptocamp/devops-stack-module-cluster-eks is now in v19.
