### ISSUE TITLE
Helm_release argocd stuck ...

### ISSUE THREAD

**Issue by armandleopold** [camptocamp/devops-stack#948]
When installing for the first time devops-stack on AKS :

The terraform plan is stuck at **helm_release.argocd**

![image](https://user-images.githubusercontent.com/7100281/199241882-8e65cc45-16c6-46ca-a06a-4245c6517c38.png)

## CrashloopPod Logs : 

```
armand [ ~ ]$ kubectl logs pod/argocd-dex-server-9cfcd548-pbpbq -n argocd
Defaulted container "dex-server" out of: dex-server, copyutil (init)
```

**Comment by armandleopold** [comment]
Found the problem : 
It was insufficent ressource allocations for the **dex-server** container : 

Cpu request 10 => 100
Memory request 32mi => 132 mi
Memory limit 64mi => 164mi

**Comment by armandleopold** [comment]
@fsismondi There is a way i can override helm config to use these settings ?

**Comment by fsismondi** [comment]
Hello @armandleopold 
you can override all params passed to helm charts using app_of_apps_values_overrides

```
app_of_apps_values_overrides = <<EOT
---
argo-cd
    dex:
      resources:
        limits:
            memory: "64Mi"
(...)

EOT
```

If you want to sneak in, and see what values is the devops stack generating before application you can :
` terraform state show module.green.module.argocd.helm_release.app_of_apps`

**Comment by armandleopold** [comment]
ok thanks !
