### ISSUE TITLE
Attach Traefik ingress controller public ip to A reccord of AZURE_DNS_ZONE

### ISSUE THREAD

**Issue by armandleopold** [camptocamp/devops-stack#949]
Hi,
I was wondering, is there a way we can add the Public IP provisionned to Traefik ingress controller at bootstrap of AKS cluster into the azurerm_dns_zone as an A reccord ?

**Comment by fsismondi** [comment]
Hello @armandleopold, sorry for the late reply. 

The creation of the traefik load balanacer automatically creates a A record in a azure DNS server.  - If I recall correctly- based on the cluster name, it creates a <something>.<region>.cloudapp.azure.com.

Does this anwer you question?

**Comment by armandleopold** [comment]
Yep ok that answer my question thank you ;-)
